---
name: "💡 Feature Request"
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out a feature request for YouCube! Please be as detailed as possible so that we can review the request easier.
        We ask that you search all the issues to avoid a duplicate feature request. If one exists, please reply if you have anything to add.
        Before requesting a new feature, please make sure you are using the latest version and that the feature you are requesting is not already present.

  - type: textarea
    attributes:
      label: Describe the feature.
      description: A clear and concise description of what you want.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Before submitting this feature request, please search our issue tracker to ensure your feature has not
        already been requested.
